### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by vladandrei14** [visanalexandru/ZooManagement#1]
1. packages should be named using only lower case characters e.g.  Animal -> animal, Zoo -> zoo
2.  Animal: make the constructor protected so only sibling could access it
3. Animal:12 (and other classes): private static int (this should be the order)
4. Leopard:33 (and other classes) : as naming convention, constants should be named using only upper case characters (and underscore instead of camelcase to separate words)

Nicely done! :sunglasses:

**Comment by visanalexandru** [comment]
Fixed in https://github.com/visanalexandru/ZooManagement/commit/02f009557ea8bf458d4ad6af7f7c5cee7273f6ba.
